### PR TITLE
add player_ids field to game_info message

### LINKED ISSUE #812: Lobby list json additional info.
May be add player id and map version id fields to lobby json?
If player change name he cant be found until re login.
Find map by name may cost a lot for server sometimes.

### PR DESCRIPTION
**Pull request by KaukaHan**
closes #812

### CODE REVIEW

**Comment by Kazbek** [comment]
May be Im wrong but as I understand we lose team info for player Id in this case. May be add grouping as in login?

**Comment by KaukaHan** [comment]
if you need that information i can add it

**Comment by Kazbek** [comment]
This will be awesome. So I can get players in team.
For better understand, its for this page https://kazbek.github.io/FAF-Analytics/lobbies

**Comment by KaukaHan** [comment]
oh my commit history got polluted again

**Comment by KaukaHan** [comment]
i opened a new clean pr

**Pull request closed without merging**
