### PR TITLE
Add version to server user connections

### PR DESCRIPTION
**Pull request by Sheikah45**

### CODE REVIEW

**Comment by Askaholic** [comment]
You also need to change the code where the metric is called to include the version

**Comment by Sheikah45** [comment]
Is this correct?

**Comment by Askaholic** [comment]
I think so. One test is failing because a mock object is missing the version field

**Comment by Sheikah45** [comment]
Alright I fixed the test. Also got the server tests running up on windows again so if anyone comes along that needs help with that I can help.

**Comment by Sheikah45** [comment]
hmmm another test is failing that doesnt fail on my setup

**Comment by Askaholic** [comment]
Yea, it's a flaky test. It will most likely pass if it runs again. I'll merge something else and you can rebase.

**Pull request merged**
