### PR TITLE
Send ID instead of name for host in gameinfo message

### PR DESCRIPTION
**Pull request by yorick-ne**
This, together with some clientside stuff should fix the announcements when a friend is hosting / playing a game.

### CODE REVIEW

**Comment by Sheeo** [comment]
I'd like to test this out on the test server before we deploy @yorick-ne -- other things may well break.

Let's get in touch saturday?

**Comment by Sheeo** [comment]
@micheljung mind checking this out on test server?

**Comment by micheljung** [comment]
ack, @Sheeo

**Comment by Sheeo** [comment]
Sparsely what needs verification is the following:

 - Replay metadata continues to contain player name in the previous place -- introducing player ID in replay metadata too would be nice. (This ensures compatibility for other tools that use them / tools that don't have the ability to lookup id -> name)
 - The various displays of `game_info` information should be unchanged

**Comment by yorick-ne** [comment]
Apparently the replay metadata is basicaly a copy of the accumulated game_info messages, so it wouldnt contain the hosts name without further adaption.
Maybe sending both name and id like 
`"host": self.host.login if self.host else '',
"host_id": self.host.id if self.host else -1,`
is better here, atleast it should have alot less potential to break stuff.

**Comment by Sheeo** [comment]
That does seem like the way to go. To be even more proper we could send a full 'player object', but this changes the type as well.

**Pull request closed without merging**
