### PR TITLE
Optimized imports

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Ran script that removes unused imports, does some ordering and normalizes newlines

### CODE REVIEW

**Comment by Sheeo** [comment]
When I made pycharm do this I had to re-import several modules afterwards. Which IDE are you using?

**Comment by JeroenDeDauw** [comment]
charm

**Comment by Sheeo** [comment]
Right, I guess it's a misconfiguration my end.

**Comment by JeroenDeDauw** [comment]
I've seen PhpStorm fail when optimizing imports in some cases, though usually it works fine. Perhaps you encountered this with an older version?

**Pull request closed without merging**
