### PR TITLE
Install aiomysql from git and re-enable warnings

### PR DESCRIPTION
**Pull request by Askaholic**
I submitted a PR to `aiomysql` to fix the deprecation warnings https://github.com/aio-libs/aiomysql/pull/403 which was merged, but hasn't been deployed as apparently the people with the ability to do so have disappeared into the void. So instead, we can just install from git to get the latest version

### CODE REVIEW

**Comment by norraxx** [comment]
What do you miss in aiomysql, that is needed for you?
Did you know, that pipenv can install from git?

**Comment by norraxx** [comment]
Do you know, that you can uninstall things that aren't used in production? For example git?

**Comment by Askaholic** [comment]
Look at the PR I linked. It generates hundreds of warnings from inside aiomysql that make it very hard to find warnings that actually are caused by our code

**Comment by norraxx** [comment]
Lol! Np :-)

**Pull request merged**
