### PR TITLE
Cleanup dependencies and imports

### PR DESCRIPTION
**Pull request by Askaholic**
Removed `-f http://content.faforever.com/wheel/` from `requirements.txt` because this page is a 403 error.

Upgraded `aiohttp` as #292 is no longer relevant.

### CODE REVIEW

**Comment by Askaholic** [comment]
It's used in `control.py` to run some sort of a server

**Comment by Rackover** [comment]
I don't know if the control server even works, I've never managed to connect to it. Did you ?

**Comment by norraxx** [comment]
It would be nice to have fully working pipenv file.

**Comment by Askaholic** [comment]
@norraxx That would be easy to set up. Is there really a big advantage though?

**Comment by norraxx** [comment]
Is there any reason, why do we use python3.5 not upper version python3.6?

**Comment by norraxx** [comment]
Yes, there is big advantage for developer.

**Pull request merged**
