### PR TITLE
More info logging

### PR DESCRIPTION
**Pull request by Askaholic**
Some changes that will make it easier to search the logs in grafana, and some changes to make it easier to correlate messages with the player that caused them. I also moved some messages into the info level that happen when people connect/disconnect. This means there will be a log message containing the IP address of everyone who connects:

```
INFO     Jan 07  13:13:13 ServerContext                  LobbyServer[SimpleJsonProtocol]: Client connected from 127.0.0.1:39214
```

### CODE REVIEW

**Comment by Sheikah45** [comment]
I don't think we want to be exposing people's IP addresses in logs that are more or less publicly viewable. I think that should probably be removed else we will have to be more secure about the logs in grafana for the server. 

@Brutus5000 what are your thoughts?

**Comment by Askaholic** [comment]
BTW, IP addresses can already show up in the logs if the connection is aborted before the player logs in.

**Comment by Sheikah45** [comment]
Then those should likely be removed as well if we don't want IPs in the logs

**Comment by Brutus5000** [comment]
As long as the sensitive logs get rotated out eventually I have no issues with logging IPs. We also keep ips for other purposes such as fraud login detection.

**Comment by Sheikah45** [comment]
Alright then wasn't sure since these logs are more widely available in grafana besides just server admins

**Comment by Askaholic** [comment]
So is this good to be merged then?

**Comment by Brutus5000** [comment]
I can't say anything from the python side of things, but sure, go ahead.

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
