### PR TITLE
Login data: test user passwords now get correctly hashed

### PR DESCRIPTION
**Pull request by Brutus5000**
Changed the insert statements to SHA2(..., 256) the test-passwords.

### CODE REVIEW

**Comment by IDragonfire** [comment]
This is the wrong place ... the files should be deleted ...
https://github.com/FAForever/db/blob/develop/db-data.sql#L263

**Comment by Brutus5000** [comment]
Done here: https://github.com/FAForever/db/pull/12.
Shouldn't the data be in sync? Otherwise we can close here.

**Comment by IDragonfire** [comment]
I am not familiar if the password is used in any tests ...Travis build has passed ...

**Comment by Sheeo** [comment]
Seems we've got a false positive travis build: https://travis-ci.org/FAForever/server/builds/130666403

Despite failing tests, the build was marked green. Hmm.

**Comment by Sheeo** [comment]
Fixed the false positive issue. I've asked travis to rebuild the PR :)

**Comment by Brutus5000** [comment]
Will probably fix login-tests tomorrow. My VM ran out of disk-space and VirtualBox doesnt expand the disk as promised :-/

**Comment by Sheeo** [comment]
Success! It failed :)

**Comment by Brutus5000** [comment]
Here we go. I haven't added salting since I didn't want to refer to the server-config in the tests.

**Comment by IDragonfire** [comment]
+1
looks good ;)

**Pull request merged**
