### PR TITLE
Feature/report teamkills

### PR DESCRIPTION
**Pull request by Brutus5000**
Depends on https://github.com/FAForever/db/pull/19 and https://github.com/FAForever/fa/pull/1293

TeamkillReport is processed and saved into database. No automatic action or reporting takes place.

### CODE REVIEW

**Comment by Brutus5000** [comment]
Build fails, because db submodule commit is not yet merged.

**Comment by IDragonfire** [comment]
You can change the Revision of the submodule to point to your db branch ;)

**Comment by Brutus5000** [comment]
I did that. On my PC everything works. But the branch is only in my fork and it looks as if travis wants to lookup the commit in the FAForever repo.

**Comment by IDragonfire** [comment]
This is true ... Atm I have no time, maybe somebody else can pull the branch to the faf repo ...

**Comment by Sheeo** [comment]
You would have to change the reference of the submodule for git to pick this up. Either way; we'll get the db one merged first then rebuild this (Which will need an update to point at the merged commit).

**Comment by micheljung** [comment]
@Sheeo is this ok to be merged?

**Comment by micheljung** [comment]
We're testing it, it's not yet ready

**Comment by micheljung** [comment]
Sucessfully tested with FA branch https://github.com/FAForever/fa/tree/release/ServerUpdateHotpatch:

```
+------------+--------+---------+----------+---------------------+
| teamkiller | victim | game_id | gametime | reported_at         |
+------------+--------+---------+----------+---------------------+
|      21447 |  76365 | 4951015 |       39 | 2016-08-07 15:45:11 |
|      76365 |  21447 | 4951015 |       27 | 2016-08-07 15:45:21 |
+------------+--------+---------+----------+---------------------+
```

**Pull request merged**
